### ISSUE TITLE
Make a gitignore file

### ISSUE THREAD

**Issue by gstark667** [bobbyplubell/2017-Robot#1]
It's annoying to leave your .class files and build directories in the repo, make a gitignore file!

**Comment by bobbyplubell** [comment]
🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆

**Comment by gstark667** [comment]
pls bobby

**Comment by maxdowling1764** [comment]
🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆

**Comment by gstark667** [comment]
🍆🍆🍆      🍆      🍆      
      🍆            🍆      🍆      
      🍆                  🍆            
      🍆                  🍆            
      🍆                  🍆
